RSS_URLS = [
    ['https://ria.ru/export/rss2/archive/index.xml', 1, 'РИА новости', 0],
    ['https://tass.ru/rss/v2.xml', 2, 'ТАСС', 0],
    ['http://www.rg.ru/xml/index.xml', 3, 'Российская газета', 0],
    ['http://www.gazeta.ru/export/rss/social.xml', 4, 'Газета.Ru', 0],
    ['https://rssexport.rbc.ru/rbcnews/news/30/full.rss', 5, 'RBC', 0],
    ['http://www.vz.ru/export/yandex.xml', 6, 'Взгляд', 0],
    ['https://lenta.ru/rss/google-newsstand/main/', 7, 'Лента', 0],
    ['http://russian.rt.com/rss/', 8, 'RT на русском', 0],
    ['https://www.mk.ru/rss/news/index.xml', 9, 'Московский Комсомолец', 0],
    ['http://kp.ru/rss/allsections.xml', 10, 'Комсомольская правда', 0],
    ['https://aif.ru/rss/googlearticles', 11, 'Аргументы и факты', 0],
    ['https://www.interfax.ru/rss.asp', 12, 'Интерфакс', 0],
    ['https://www.rosenergoatom.ru/zhurnalistam/news/rss/', 13, 'Росатом', 0],
    ['https://www.atomic-energy.ru/news/rss.xml', 14, 'Атомная энергия', 0],
    ['https://www.vedomosti.ru/rss/articles', 15, 'Ведомости', 0],
    ['https://news.ru/rss/type/post/', 16, 'NEWS.ru', 0],
    ['https://news.rambler.ru/rss/world/', 17, 'Рамблер', 0],
    ['https://www.kommersant.ru/RSS/news.xml', 18, 'Коммерсант', 0],
    ['https://globalvoices.org/-/world/western-europe/feed/', 19, 'gv_western-europe', 1],
    ['https://globalvoices.org/-/world/middle-east-north-africa/feed/', 20, 'gv_middle-east-north-africa', 1],
    ['https://globalvoices.org/-/world/north-america/feed/', 21, 'gv_north-america', 1],
    ['https://globalvoices.org/-/world/latin-america/feed/', 22, 'gv_latin-america', 1],
    ['https://globalvoices.org/-/world/eastern-central-europe/feed/', 23, 'gv_eastern-central-europe', 1],
    ['https://globalvoices.org/-/world/central-asia-caucasus/feed/', 24, 'gv_central-asia-caucasus', 1],
    ['https://globalvoices.org/-/world/east-asia/feed/', 25, 'gv_east-asia', 1],
    ['https://globalvoices.org/-/topics/war-conflict/feed/', 26, 'gv_war-conflict', 1],
    ['https://globalvoices.org/-/topics/technology/feed/', 27, 'gv_technology', 1],
    ['https://globalvoices.org/-/topics/science/feed/', 28, 'gv_science', 1],
    ['https://globalvoices.org/-/topics/politics/feed/', 29, 'gv_politics', 1],
    ['https://globalvoices.org/-/topics/health/feed/', 30, 'gv_health', 1],
    ['https://globalvoices.org/-/topics/development/feed/', 31, 'gv_development', 1],
    ['https://globalvoices.org/-/topics/breaking-news/feed/', 32, 'gv_breaking-news', 1],
    ['https://globalvoices.org/-/topics/disaster/feed/', 33, 'gv_disaster', 1],
]

