RSS_URLS = [
    ['https://ria.ru/export/rss2/archive/index.xml', 1, 'РИА новости'],
    ['https://tass.ru/rss/v2.xml', 2, 'ТАСС'],
    ['http://www.rg.ru/xml/index.xml', 3, 'Российская газета'],
    ['http://www.gazeta.ru/export/rss/social.xml', 4, 'Газета.Ru'],
    ['https://rssexport.rbc.ru/rbcnews/news/30/full.rss', 5, 'RBC'],
    ['http://www.vz.ru/export/yandex.xml', 6, 'Взгляд'],
    ['https://lenta.ru/rss/google-newsstand/main/', 7, 'Лента'],
    ['http://russian.rt.com/rss/', 8, 'RT на русском'],
    ['https://www.mk.ru/rss/news/index.xml', 9, 'Московский Комсомолец'],
    ['http://kp.ru/rss/allsections.xml', 10, 'Комсомольская правда'],
    ['https://aif.ru/rss/googlearticles', 11, 'Аргументы и факты'],
    ['https://www.interfax.ru/rss.asp', 12, 'Интерфакс'],
    # ['https://www.rosenergoatom.ru/zhurnalistam/news/rss/', 13, 'Росатом'],
    # ['https://www.atomic-energy.ru/news/rss.xml', 14, 'Атомная энергия'],
    # ['https://www.vedomosti.ru/rss/articles', 15, 'Ведомости'],
    # ['https://news.ru/rss/type/post/', 16, 'NEWS.ru'],
    # ['https://news.rambler.ru/rss/world/', 17, 'Рамблер'],
    # ['https://www.kommersant.ru/RSS/news.xml', 18, 'Коммерсант'],
]

